[package]
name = "swww-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithay-client-toolkit = { version = "0.16", default-features = false, features = ["calloop"] }
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
keyframe = "1.1"

utils = { path = "../utils" }
sd-notify = { version = "0.4.1" }

[dev-dependencies]
rand = "0.8"
