[package]
name = "swww-daemon"
version = "0.9.0"
authors = ["Leonardo Gibrowski Fa√© <leonardo.fae44@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
simplelog = "0.12"

wayland-client = { version = "0.31", default-features = false, features = [ "log" ]}
smithay-client-toolkit = { version = "0.18", default-features = false }

nix = { version = "0.28", default-features = false, features = [ "signal", "poll" ] }
keyframe = "1.1"
rkyv = "0.7"
rayon = "1.9"
spin_sleep = "1.2"

sd-notify = { version = "0.4.1" }

utils = { version = "0.9.0", path = "../utils" }
[dev-dependencies]
rand = "0.8"
