[package]
name = "utils"
version = "0.8.0"
authors = ["Leonardo Gibrowski Fa√© <leonardo.fae44@gmail.com>"]
edition = "2021"

[dependencies]
lazy_static = "1.4"
lzzzz = "=1.0.4"
rkyv = "0.7"

[dev-dependencies]
rand = "0.8"
criterion = "0.5"

[[bench]]
name = "compression"
harness = false
